### ISSUE TITLE
Mupen64Plus-Next not working

### ISSUE THREAD

**Issue by Broos-E** [asakous/Neo-EmuELEC-H3#1]
when Mupen64Plus-Next is selected as core it just goes back to emulationstation

Orangepi PC

**Comment by asakous** [comment]
please provide logs. 
read https://github.com/EmuELEC/EmuELEC/wiki . in  Need help? section

**Comment by Broos-E** [comment]
EmuELEC Run Log
##############################################
#                 EmuELEC                    #
#     Retro emulation for Amlogic Devices    #
#             Based on CoreELEC              #
##############################################
EmuELEC (Community - EmuELEC is FREE! NOT FOR SALE!): 3.7 (H3.arm)
PLATFORM: n64
ROM NAME: /storage/roms/n64/Mario Kart 64 (USA).n64
BASE ROM NAME: Mario Kart 64 (USA).n64
USING CONFIG: /storage/.config/retroarch/retroarch.cfg
1st Argument: /storage/roms/n64/Mario Kart 64 (USA).n64
2nd Argument: -Pn64
3rd Argument: --core=mupen64plus_next
4th Argument: --emulator=libretro
Full arguments: /storage/roms/n64/Mario Kart 64 (USA).n64 -Pn64 --core=mupen64plus_next --emulator=libretro --controllers=-p1index 0 -p1guid 03000000790000001c18000011010000 
Run Command is:
/usr/bin/retroarch -v -L /tmp/cores/mupen64plus_next_libretro.so --config /storage/.config/retroarch/retroarch.cfg /storage/roms/n64/Mario Kart 64 (USA).n64
Emulator Output is:
[INFO] RetroArch 1.8.9 (Git a308be6)
[INFO] [Overrides]: Redirecting save file to "/storage/roms/n64/Mario Kart 64 (USA).srm".
[INFO] [Overrides]: Redirecting save state to "/storage/roms/n64/Mario Kart 64 (USA).state".
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Sep  8 2020
[INFO] Version: 1.8.9
[INFO] Git: a308be6
[INFO] =================================================
[INFO] [CORE]: Loading dynamic libretro core from: "/tmp/cores/mupen64plus_next_libretro.so"
[INFO] [Overrides]: No core-specific overrides found at /storage/.config/retroarch/config/Mupen64Plus-Next/Mupen64Plus-Next.cfg.
[INFO] [Overrides]: No content-dir-specific overrides found at /storage/.config/retroarch/config/Mupen64Plus-Next/n64.cfg.
[INFO] [Overrides]: No game-specific overrides found at /storage/.config/retroarch/config/Mupen64Plus-Next/Mario Kart 64 (USA).cfg.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: SET_CORE_OPTIONS.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Remaps]: remap directory: /storage/remappings
[INFO] [Overrides]: Redirecting save file to "/storage/roms/n64/Mario Kart 64 (USA).srm".
[INFO] [Overrides]: Redirecting save state to "/storage/roms/n64/Mario Kart 64 (USA).state".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: GET_PERF_INTERFACE.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [CONTENT LOAD]: Loading content file: /storage/roms/n64/Mario Kart 64 (USA).n64.
[INFO] Did not find a valid content patch.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGLES2 context.
[libretro INFO] mupen64plus: Using full mem base
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[libretro INFO] mupen64plus: Goodname: Mario Kart 64 (U) [!]
[libretro INFO] mupen64plus: Name: MARIOKART64         
[libretro INFO] mupen64plus: MD5: 3A67D9986F54EB282924FCA4CD5F6DFF
[libretro INFO] mupen64plus: CRC: 3E5055B6 2E92DA52
[libretro INFO] mupen64plus: Imagetype: .v64 (byteswapped)
[libretro INFO] mupen64plus: Rom size: 12582912 bytes (or 12 Mb or 96 Megabits)
[libretro INFO] mupen64plus: ClockRate = F
[libretro INFO] mupen64plus: Version: 1446
[libretro INFO] mupen64plus: Manufacturer: Nintendo
[libretro INFO] mupen64plus: Cartridge_ID: 544B
[libretro INFO] mupen64plus: Country: USA
[libretro INFO] mupen64plus: PC = 80000400
[libretro INFO] mupen64plus: Save type: 0
[INFO] [SRAM]: Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /tmp/database/cht/Mupen64Plus-Next/Mario Kart 64 (USA).cht
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [Video]: Using configured "gl" driver for GL HW render.
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [GL]: Found GL context: fbdev_mali
[INFO] [GL]: Detecting screen resolution 0x0.
[INFO] [EGL]: Current context: 0x40000001.
[INFO] [GL]: Vendor: ARM, Renderer: Mali-400 MP.
[INFO] [GL]: Version: OpenGL ES 2.0.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 1 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Initializing HW render (1024 x 1024).
[INFO] [GL]: Max texture size: 4096 px, renderbuffer size: 4096 px.
[INFO] [GL]: Supports FBO (render-to-texture).
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: Pad #0 (/dev/input/event4) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [Video]: Found display server: null
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 384 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Environ]: SET_SUBSYSTEM_INFO.
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [Playlist]: Written to playlist file: /storage/.config/retroarch/content_history.lpl
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[libretro INFO] mupen64plus: Game controller 0 (Standard controller) has a Memory pak plugged in
[libretro INFO] mupen64plus: Game controller 1 (Standard controller) has nothing plugged in
[libretro INFO] mupen64plus: Game controller 2 (Standard controller) has nothing plugged in
[libretro INFO] mupen64plus: Game controller 3 (Standard controller) has nothing plugged in
[libretro INFO] mupen64plus: Using CIC type X102
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
Segmentation fault (core dumped)
exit 1

**Comment by asakous** [comment]
It seems a upstream problem.
[https://github.com/libretro/mupen64plus-libretro-nx/issues/260](url)

I also compiled many version of mupen64plus-nx .  after [9f3169220042edf215c0b3c1a93a09e506a1e19c] commit. the emulator on H3 platform start to crash.

**Comment by asakous** [comment]
I temporary rollback mupen64plus-next version. and I tested Super Mario 64. it seems OK to me.

**Comment by asakous** [comment]
it's a mupen64plus-next problem. old version seems OK. but new version will crash.
