### ISSUE TITLE
Error loading roms

### ISSUE THREAD

**Issue by archeart23** [asakous/Neo-EmuELEC-H3#12]
![IMG_20201128_145806](https://user-images.githubusercontent.com/19247332/100495940-1657cc80-318b-11eb-8be1-5ae1920cf98d.jpg)

![IMG_20201128_145827](https://user-images.githubusercontent.com/19247332/100495947-22438e80-318b-11eb-84ae-e7c06a647351.jpg)

![IMG_20201128_145834](https://user-images.githubusercontent.com/19247332/100495955-2e2f5080-318b-11eb-89ef-60bbc55a1431.jpg)

Some ROMs don't work when in rom form but the zips I've tried just won't work hmmmm ...

I'll try to do a comprehensive analysis using one system at a time

**Comment by archeart23** [comment]
ok so far my conclusion is .rar files via winrar causes issues but if made into zip its fine.. i also added .rar and .RAR to extensions but just wont work properly so decided to use .zips instead.. as for the loading issue seems to be a bios mismatch going to create a new collection for BIOS and give you the documentation.

**Comment by archeart23** [comment]
![image](https://user-images.githubusercontent.com/19247332/100514616-4023ea00-31b1-11eb-93de-0ea9124149ab.png)


please edit that section and remove gearsystem since that doesnt work with mastersystem... made me go crazy with this error
uploaded the working one for now :P 

[es_systems.zip](https://github.com/asakous/Neo-EmuELEC-H3/files/5610509/es_systems.zip)

**Comment by asakous** [comment]
according to [Libretro docs  ](https://docs.libretro.com/library/gearsystem/)Master System should work. unless there are some other issues. and  there is no one reported this issus in EmeELEC.

**Comment by asakous** [comment]
the first run seems to be ok. and the second  run will got killed. because core eat too many memory.

error log
Out of memory: Kill process 1199 (retroarch) score 278 or sacrifice child

**Comment by asakous** [comment]
will be fixed  in next release

**Comment by archeart23** [comment]
> will be fixed in next release

Yeh sometimes the error appears when I exit a game or do something like check system info

**Comment by archeart23** [comment]
I've done testing all my fbneo and mame games around a few thousand and I'm happy that almost all the games I like have been fixed I've managed to narrow it down to around 1k games for my fbneo and mame, the glitch is still there for some and had to use other cores to play them and ofc having the right bios like pgm for example is a must.

Still wasn't able to get gearsystem to work for me even with trying different bios and ROMs so I guess it's a memory issue as you stated

When you release new version I hope you can list out all changes to cores, is it possible to have two versions of the same core btw? Would be nice if you could release a test version with that so I can help out

**Comment by asakous** [comment]
fixed in v1.3.
