### ISSUE TITLE
Only hdmi sound work? 

### ISSUE THREAD

**Issue by archeart23** [asakous/Neo-EmuELEC-H3#13]
So I'm trying to get my speakers to work but for some reason only hdmi sound works and can't find settings to change to speakers....

Hope you can help me out 
Thanns

**Comment by asakous** [comment]
there is no GUI interface to change it. You have to use ssh client to login orangepi and change config below.


~/.config/emuelec/configs/emuelec.conf

Audio device to use, comment for auto, other options 0,0 (default) 0,1 (for some AV outputs)
#ee_audio_device=auto -->ee_audio_device=0,1
and 
~/.config/retroarch/retroarch.cfg
audio_device = "hw:1,0"-->hw:0,1
