### ISSUE TITLE
Can't change resolution to 720p60 in Orangepip2e

### ISSUE THREAD

**Issue by zarkon0** [asakous/Neo-EmuELEC-H3#14]
Hi.

From the menu I change the resolution to 720p60 and restart Orangepi Plus 2e but the resolution still 1080p instead 720p.

Thanks!

**Comment by asakous** [comment]
You need to modify script.bin file. please reference [Fex Guide](https://linux-sunxi.org/Fex_Guide) . in [disp_init] section

**Comment by zarkon0** [comment]
Yes, I already knew that I can change the resolution in that file.
I thought that option on the menu should be functional.

Thank you.

**Comment by asakous** [comment]
that option is specific for Amlogic. it should be removed in the future. 
or I put h3disp script into image in case some one want to change resolution .

**Comment by asakous** [comment]
I forgot . the h3disp already in /usr/sbin.  but I never use it. please backup script.bin before use it.
