### ISSUE TITLE
Install neo emuelec to eMMC in OrangepiPlus2e

### ISSUE THREAD

**Issue by zarkon0** [asakous/Neo-EmuELEC-H3#15]
Hi.

Is possible to install neoemuelec into eMMC in OrangePi Plus 2e?

Thanks.

**Comment by asakous** [comment]
sorry I don't know how to do that.
but I do found a link https://forum.libreelec.tv/thread/20556-libreelec-installation-for-nand-at-mini-mx-s905/
### Use it at your own risk
