### ISSUE TITLE
Retroarch won't save? 

### ISSUE THREAD

**Issue by archeart23** [asakous/Neo-EmuELEC-H3#16]
For some reason my settings won't save in retroarch I tried what you said in the other report you closed.

On a side note, remember my question about changing the audio device, looks like also need to change emulation station audio device since default was PCM.

**Comment by asakous** [comment]
retroarch settings can be modified through it's GUI interface or vi editor. I believe you did something wrong. 
and please read emuelec.conf. it has all default config setting for the system . 
for example 
ee_alsa.always=0
ee_audio_device=auto
these settings  are responsible for  sound. you can try different combination
for the ES . there is a option for the sound device.

**Comment by archeart23** [comment]
I've managed to solve this with fresh install and opening/show force core and game saves
