### ISSUE TITLE
Ports won't go away

### ISSUE THREAD

**Issue by archeart23** [asakous/Neo-EmuELEC-H3#17]
I don't need ports for what I want and for some reason I can't get rid of them lol.

I've tried deleting in ES and even in winscp..

I can take out the system for it so it doesn't show anymore but I don't want it taking up the space of my small sd card...

**Comment by asakous** [comment]
remove related settings in  es_systems.cfg file

**Comment by archeart23** [comment]
> remove related settings in es_systems.cfg file

Done just that and also for the other two emulators that won't go away... 

Still curious why I can't delete them from the roms folder tho lol

**Comment by asakous** [comment]
you  can delete them if you want. it won't break the system.
