### ISSUE TITLE
KMFDMANIC SPEEDHACKS

### ISSUE THREAD

**Issue by archeart23** [asakous/Neo-EmuELEC-H3#18]
https://github.com/KMFDManic/NESC-SNESC-Modifications/tree/v.3.8-10-06-2020

Have you tried those emulators/cores?

I've heard the flycast and reicast make the games smoother!
Perhaps you can try it out? 

I'm trying to learn how to do it too so I can help!

**Comment by asakous** [comment]
flycast and flycast standalone will be included in next release.
