### ISSUE TITLE
Th strikes back and other driver issues

### ISSUE THREAD

**Issue by archeart23** [asakous/Neo-EmuELEC-H3#19]
I've been testing all the games I've got and found glitches on alot of them but this particular one got me working on it for hours and it turns out the .cpp for thoop2 is the wrong one, the fbneo has the right one for it tho just mame2003+ having issues with it.

Also one worthy of note is mach breakers numan athletics 2 having no sounds on mame2003+ but have sound on another emulator on my pc, is there no way to change drivers without recompiling? Since I don't got a clue on how to do that yet 😂

**Comment by asakous** [comment]
as you stated. you better report to libretro. not here.  since it's a emulator core problem. I can't solve it too.
as far as I know , some games work on one emulator and doesn't work on other emulator., It's normal . that's why you need to switch games to different emulator.
