### ISSUE TITLE
Internet connection not working

### ISSUE THREAD

**Issue by Broos-E** [asakous/Neo-EmuELEC-H3#2]
Not getting any connection to the internet, i can transfer files over wifi but cant connect to the internet, when i try to install Drastic it says am i sure i am connected to the internet

**Comment by asakous** [comment]
drastic install script is provided by EmuELEC. I didn't change it. If I were you, I would try to ssh to console  and see what ip and gateway that console got.  or just  ping google.com and see what happened  .

**Comment by Broos-E** [comment]
cant download any themes either. what command do i use to see ip and gateway?   cheers

**Comment by asakous** [comment]
ifconfig

**Comment by Broos-E** [comment]
Emuelec:~ # ifconfig
eth0      Link encap:Ethernet  HWaddr 4E:2F:46:1A:D1:22
          inet addr:192.168.1.98  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:71054 errors:0 dropped:18 overruns:0 frame:0
          TX packets:13999 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:8183949 (7.8 MiB)  TX bytes:5724582 (5.4 MiB)
          Interrupt:114

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:192 errors:0 dropped:0 overruns:0 frame:0
          TX packets:192 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:13612 (13.2 KiB)  TX bytes:13612 (13.2 KiB)

Emuelec:~ # ^C
Emuelec:~ #

**Comment by asakous** [comment]
type 
ip r | grep default

**Comment by Broos-E** [comment]
Emuelec:~ # ip r | grep default
default via 192.168.1.254 dev eth0

**Comment by asakous** [comment]
does all IPs are correct for your home network? because  Emuelec has own IP and gateway .but you cant get internet access .  that means you probably miss gateway or firewall NAT configuration .

**Comment by Broos-E** [comment]
sorry im not sure what you mean. everything else i have with emuelec works fine its just the orangepi pc that wont.  cheers

**Comment by asakous** [comment]
sorry . I can't help you . I believe it's a network  configuration problem. my suggestion is plug your emuelec(not H3) and type [ip r | grep default] does it show any differences . if the same then check your router . does if block unknow device for internet access.

**Comment by Broos-E** [comment]
ok no worries its not such a big deal.  cheers
