### ISSUE TITLE
Can't get bezels to work

### ISSUE THREAD

**Issue by archeart23** [asakous/Neo-EmuELEC-H3#21]
Can't get bezels to work..

Placed them in bezel folder and also retroarch but not working. ...

Any idea?

**Comment by asakous** [comment]
please read 
https://github.com/EmuELEC/EmuELEC/wiki/Bezels-&-Splash-screens

**Comment by archeart23** [comment]
Having issues still.. weird, I'll try bezel project again if it will work

**Comment by asakous** [comment]
No response for long time . close for now.
