### ISSUE TITLE
Underclock / Undervolt Allwinner H3

### ISSUE THREAD

**Issue by hmvendramini** [asakous/Neo-EmuELEC-H3#22]
Hello everyone!

I'm running Emuelec on an Orange Pi lite, and it looks great :)

The board is in a closed case, with temperatures reaching 83º ... is it possible to decrease the clocks or voltages of the processor so that it can work cooler?

Let me know if I posted in the wrong place, this is my first post ...

Thanks to everyone who can participate :)

**Comment by asakous** [comment]
change CPU governor  from performance to ondemand in custom_start.sh

**Comment by hmvendramini** [comment]
Hello, Thanks for the feedback. I'm doing some tests, but for now, with no effects ...

**Comment by asakous** [comment]
maybe your heatsink  too small.

**Comment by asakous** [comment]
no response for long time . close for now.
