### ISSUE TITLE
Vram 180?

### ISSUE THREAD

**Issue by archeart23** [asakous/Neo-EmuELEC-H3#23]
Hi! 
Thanks for the update just want to give my feedback..

Seems very sluggish and had to change vram.

Could not play any games it just kept loading then black screen..

The sound issue fix in this release tho! Awesome

**Comment by asakous** [comment]
I need more information. ex. dmesg. emuelec log . and this release  seems ok on my orange pi pc

**Comment by asakous** [comment]
no response . close for now.
