### ISSUE TITLE
can't change video resolution in orangepipc

### ISSUE THREAD

**Issue by jkoroso** [asakous/Neo-EmuELEC-H3#24]
Hi, congratulations this system is increible, is better than retrorangepi

 i am trying ti change video resolution to 1680 x 1050 for my 22" display

i try 3 options:

1- change in emulation station menu to autodetec resolution, dont work

2 - i try as the emuelec wiki says , but in Emuelec partition dont find config.ini file, i create it and set hdmimode=1680p60hz, them go to .config/emuelec/configs and open emuelec.conf. In here, set ee_videomode=1680p60hz. dont work

3 - in forum discussion i read to create EE_VIDEO_MODE file in emuelec boot partition and set 1680x1050p@60hz , dont work

thanks

**Comment by asakous** [comment]
the options are specific for Amlogic chip  .  I still thinking to remove it from menu. 
according to  [Allwinner Fex_Guide](https://linux-sunxi.org/Fex_Guide#disp_init_configuration) . seem not support 1680p60hz resolution. 
you may try h3disp 
 I already put h3disp in the image.  good lock.

**Comment by jkoroso** [comment]
thanks, i used h3disp in retrorange pi an works fine, but in neoemulec i recevive this error

Emuelec-H3:~ # h3disp -m 36
Now trying to patch script.bin with your settings. Aborted
Could not convert script.bin to fex. Exiting

**Comment by asakous** [comment]
I think it's a bug . I should put some related files into image too.

**Comment by jkoroso** [comment]
thanks
