### ISSUE TITLE
Background sounds do not work

### ISSUE THREAD

**Issue by eltonds** [asakous/Neo-EmuELEC-H3#25]
Background sounds do not work. I put music in ogg format in the folder /storage/roms/BGM and set Frontend music and it doesn't work.
1. Put music in the folder
2. Go to 'Main Menu'
3. Click on 'sound settings'
4. Set Frontend music

Emuelec 3.9 on Orange PI PC

**Comment by asakous** [comment]
probably because I disabled pulseaudio .  it eat too much cpu power and cause sound delay.  H3 is slow then S905X.

**Comment by asakous** [comment]
added in v2.0
