### ISSUE TITLE
Erro orangepi one

### ISSUE THREAD

**Issue by Ascender1988** [asakous/Neo-EmuELEC-H3#26]
![be6f2840-ad96-42a9-915a-bd5a5e04dea5](https://user-images.githubusercontent.com/81423852/112693172-eed5ef80-8e5e-11eb-8397-b4066297c1b8.png)

It installs well but when shutting down it no longer starts

**Comment by asakous** [comment]
my orange pi doesn't have this problem. bad sd card perhaps. try change another sd card.

**Comment by asakous** [comment]
no response for 14 days . close for now
