### ISSUE TITLE
Drastic: no sound in games!

### ISSUE THREAD

**Issue by batistars** [asakous/Neo-EmuELEC-H3#29]
I installed Drastic, ran the games very well, but without sound, what can it be? Is there a solution for that?

**Comment by asakous** [comment]
plug a speaker into jack 3.5mm . maybe the default sound setting is from there.

**Comment by batistars** [comment]
> conecte um alto-falante na tomada de 3,5 mm. talvez a configuração de som padrão seja de lá.

But is there no way to change this in the system? In the other emuladires it is normal. I will try to do what you said.

**Comment by asakous** [comment]
sorry I don't play NDS.
but 
Drastic is a stand along emulator. it has it's own configuration and it control by emulator itself.  I think drastic should have a audio option  on the drastic emulator menu.

**Comment by asakous** [comment]
I just found a video . this may help you https://www.youtube.com/watch?v=GozAo2pKvuo

**Comment by asakous** [comment]
no response for  14 days . close for now.
