### ISSUE TITLE
PIXEL Theme.

### ISSUE THREAD

**Issue by lamerjack** [asakous/Neo-EmuELEC-H3#3]
I just installed from menu the theme PIXEL and PIXEL tft.
but if i enable it there is no graphics, only text.

**Comment by Broos-E** [comment]
redownload it as sometimes it does not install properly

**Comment by lamerjack** [comment]
Is an internet problem!
I can connect via ssh, i can ping other systems. The gateway is correct...
But doesnt go to internet!
also wget fail.
Broos-E i saw that you had internet issue how did you solved?

**Comment by Broos-E** [comment]
i didnt solve the ethernet connection problem but used a wifi dongle instead to connect to the internet

**Comment by asakous** [comment]
will be fixed next release.

**Comment by asakous** [comment]
new image released should fixed this problem
