### ISSUE TITLE
AllWinner H3 SoC Model Support

### ISSUE THREAD

**Issue by jayjaydluffy** [asakous/Neo-EmuELEC-H3#32]
Hey @asakous, if you could kindly lead me to the correct release for my Android TV Box that has specs in [this screenshots](https://scontent.fmnl4-1.fna.fbcdn.net/v/t1.15752-9/s2048x2048/184602840_2551932821769467_7835754686849235933_n.jpg?_nc_cat=109&ccb=1-3&_nc_sid=ae9488&_nc_eui2=AeFL3rGjDXALgl_owK623ro9FwHjQlRpz08XAeNCVGnPTzmtqjh43oOjInwP8B3KUkQ&_nc_ohc=BM9RHN-4Sl8AX-FUdbl&_nc_ht=scontent.fmnl4-1.fna&tp=7&oh=03d01f54cd896d920fa37e77b91d6a6a&oe=60BF0AA7) and [this](https://scontent.fmnl4-1.fna.fbcdn.net/v/t1.15752-9/s2048x2048/185201561_483601356026837_7583829296859084635_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=ae9488&_nc_eui2=AeFOUP0MP-R_PDzZz7bBYFDU1QP8tcRojdXVA_y1xGiN1emTF7-nc4aCt4c4qZhQDXU&_nc_ohc=IErCqEZ200oAX--JWeL&_nc_ht=scontent.fmnl4-1.fna&tp=7&oh=ce2548e96c294fa2e5452074380c37b4&oe=60BD35FA)

I've tried **EmuELEC-H3.arm-4.0-bpim2p.img.gz** but it didn't work when I boot it up in **LibreELEC**. 

Thank you in advance!

**Comment by asakous** [comment]
sorry I don't know how to make H3 android TV boxes dual boot.
