### ISSUE TITLE
Missing DTB explanation

### ISSUE THREAD

**Issue by d-apps** [asakous/Neo-EmuELEC-H3#34]
It would be great if we could have a "How to Install" section for Allwinner H3 devices in read me.

Is DTB necessary to h3 devices? Since we aren't using an Amlogic device I don't know what to do about that, it is necessary according to emuELEC wikia. [https://github.com/EmuELEC/EmuELEC/wiki/How-to-Install](url)

**Comment by asakous** [comment]
DTB file is not necessary .
just download released file that match your H3 board.
decompress the file.
use win32DISKImager write it to sd card
that it.
Note: android TV boxes are not supported.

**Comment by d-apps** [comment]
I am using on my plus 2e, amazing work!
Now I am testing the emulators, thanks a lot!
