### ISSUE TITLE
Connect on VGA monitor with HDMI x VGA adapter without video

### ISSUE THREAD

**Issue by Nill2016** [asakous/Neo-EmuELEC-H3#37]
I tried to connect my Orange PI Plus 2e on a VGA monitor as an HDMI X VGA Ugreen and Vention adapter and appears on the screen that is not supported. Is there any configuration to correct this problem?!

**Comment by asakous** [comment]
try use h3disp to change script.bin resolution configs

**Comment by asakous** [comment]
no response for 10 days. closed
