### ISSUE TITLE
GPIO activation

### ISSUE THREAD

**Issue by diversaoretro** [asakous/Neo-EmuELEC-H3#38]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**EmuELEC version:**
 - Neo-EmuELEC-H3 V2.0

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
Orangepi PC

**Additional context**
I enter the configuration option and go to the option to enable GPIO, but GPIO does not enable.

**Comment by asakous** [comment]
a python package is missing. please use old version if you need GPIO service or wait for next release.

**Comment by asakous** [comment]
please test new version v4.2
