### ISSUE TITLE
Neither by IP nor by Host does not have access to system folders.

### ISSUE THREAD

**Issue by diversaoretro** [asakous/Neo-EmuELEC-H3#39]
Neo-EmuELEC-H3 V4.2
Orangepi PC

hello good night, I installed the new version of emuelec for orangepi PC with the GPIO correction, but neither by IP nor by Host I can't access the folders over the network.

**Comment by asakous** [comment]
You should able connect to orangepi PC by using SSH or SCP.  
go to ES menu  and see what IP you got.
or simply  use NTFS as storage filesystem.  please reference https://github.com/EmuELEC/EmuELEC/releases/tag/v4.2

**Comment by asakous** [comment]
since I use network dongle  at home  and I don't have the problem you mentioned . maybe you can try plug wire/usb dongle  before boot up.
