### ISSUE TITLE
Emuelec sem som

### ISSUE THREAD

**Issue by batistars** [asakous/Neo-EmuELEC-H3#40]
Baixei o emuelec 4.2 e ta sem som. Sabe como resolver isso? Sera que tem a ver com o alsamixer, dei uma olhada na Internet e achei alguma coisa relacionada a isso, mas como entro no terminal para acessar o alsamixer? Uso a Orange pi Pc

I downloaded emuelec 4.2 and there is no sound. Do you know how to solve this? Does it have to do with alsamixer, I took a look on the Internet and found something related to it, but how do I enter the terminal to access alsamixer?

**Comment by asakous** [comment]
which one did you use. HDIM output or 3.5 jacks ?  and is emulator no sound or emulationstation one?

**Comment by batistars** [comment]
HDMI. Ta sem som em todo sistema, emulationstation e nos emuladores ( jogos )

**Comment by asakous** [comment]
The image should work out of box. 
anywhere
bring out Retroarch menu . and try config audio_device to  hw:0,0 or  hw:0,1 and save ,reboot . play a rom and see what happen.

**Comment by batistars** [comment]
No retroarch consegui fazer funcionar, mas o emulationstation consegui uma vez, então fui olhar e agora ta sem som, não sei o que pode ser, ja usei todaa opções, 0.0, 0.1, 1.0, 1.1 e auto

**Comment by asakous** [comment]
try  fix Retroarch first. because ES and RA sound settings seems separately. another word. ES setting may not affect RA.

**Comment by diversaoretro** [comment]
> 
> 
> The image should work out of box.
> anywhere
> bring out Retroarch menu . and try config audio_device to hw:0,0 or hw:0,1 and save ,reboot . play a rom and see what happen.

Aqui deu Certo no ES deixa 1,1 e no RO deixa hw:1,0  tambem

**Comment by asakous** [comment]
English please.

**Comment by diversaoretro** [comment]
> 
> 
> English please.

Here it worked in ES it leaves 1.0 and in RO it leaves hw:1.0 too

**Comment by asakous** [comment]
there is a file you need to check  
asound.conf . you may need to change too.

**Comment by diversaoretro** [comment]
> asound.conf

here there was no need to change the asound.conf file.

**Comment by SeolAJ** [comment]
I have the same issue here, but I use an k36, a clone from r36s. I don't know how to configure the driver's. My system is a emuelec 4.7, I watched too many videos and also read the forums, but no one has the same problem as me.
I did the path through the retroarch, but still confused about how to solve this.

**Comment by asakous** [comment]
y

> I have the same issue here, but I use an k36, a clone from r36s. I don't know how to configure the driver's. My system is a emuelec 4.7, I watched too many videos and also read the forums, but no one has the same problem as me. I did the path through the retroarch, but still confused about how to solve this.

sorry I don't know  k36 retro handheld  . You may ask offcial EmuELEC for helps.
