### ISSUE TITLE
Jamma controller

### ISSUE THREAD

**Issue by Fran77cl** [asakous/Neo-EmuELEC-H3#41]
Hello, I download neo emuelec image for orangepi H3, for a Pandora with Allwinner H3 processor with jamma connector.  I have the jamma board wired with 2 arcade stick controllers plus a USB controller connected to the only available port and RetroArch and emeulec recognizes 3 controllers, but it only lets me configure the USB controller.  When I want to configure the arcades stick it does not recognize any button, but it does recognize them as TZGamesS 1 and TzGamesS2.  It are recognized with the udev and sl2 driver.  But with the Parport it recognizes 16 ports (one for each button), do you have any idea what to do to be able to use the arcade sticks wired by jamma?  Thank you

**Comment by asakous** [comment]
sorry I have not idea. but this version it does support GPIO arcade stick. you may want to try it.

**Comment by Fran77cl** [comment]
Thanks for your answer. This version support Jamma connection? No GPIO.

**Comment by asakous** [comment]
Probably not. You have to finger out by yourself . I don't have any Jamma controller . even I have ideas I can't test it.
