### ISSUE TITLE
H3 Orangepi one

### ISSUE THREAD

**Issue by asegura02** [asakous/Neo-EmuELEC-H3#42]
i was trying your your rom but is not working on my OPI

I use RetrOrangePi and the way they was able to run on the OPI one , is they have a modded the  Mali.ko Gpu controller  , also they created a swap file. Then on my side i added a extra swap partition and moded the fstab so i use the same sdcard with 2 parttion so this helps in memory issues  , maybe you can try adding this swap memory and the modded mali.ko file for the GPU and give it a try ! Probably even help on the more poweful boards , i have with retrorage pi running psx like a charm , but is outdated already :D

**Comment by asakous** [comment]
use this  https://github.com/asakous/Neo-EmuELEC-H3/releases/tag/H3-v2.0 . there is a image for  Orangepi one

**Comment by asegura02** [comment]
Thanks im doing some testing , is possible to edit the etc\fstab , because seems to be read only

**Comment by asakous** [comment]
no. you can't . if you want to mount usb driver. try read this https://github.com/EmuELEC/EmuELEC/wiki/ROMS-on-USB-media

**Comment by asakous** [comment]
remember . because opi one only has 512mb of  ram . don't use default theme. it eats a lot of memory and cause some memory issues . try download new theme from ES menu. usually it will solve memory problems.

**Comment by asegura02** [comment]
i was trying to add a swap parttition i created 
UUID=b6afdcc6-81e5-4e42-bca0-374b1b1091fc / swap
sw

**Comment by asakous** [comment]
put you command in autostart.sh or custom_start.sh . it will run on boot.

**Comment by asegura02** [comment]
Thanks for your help , seems i need to stick to retrorangepi , still cannot make emuelec run fine on my old board hehe
