### ISSUE TITLE
Hi Bluetooth issue

### ISSUE THREAD

**Issue by asegura02** [asakous/Neo-EmuELEC-H3#44]
Hi i have , a sunvell r69 , i got it working with the Banana pi img everything works fine , but i only can pair one bluetooth controller, i have tested the controller with other box so is not a controller issue  , probably some fex value or emuelec config , but i not programmer, is it possible to build a sunvell r69 version? or maybe you can poit me what to do , thanks

**Comment by asegura02** [comment]
I tried the  steps show here  https://github.com/EmuELEC/EmuELEC/wiki/Bluetooth#notes--ps3-controllers

it does pair using the teminal emulator using the command bluetoothctl
default-agent
power on
discoverable on
pairable on
scan on
after i get the BT mac i enter  
trust <BTMAC>
connect <BTMAC>
but when i go back to Emuelec it disconects and don´t want to pair , Only one controller works

**Comment by asegura02** [comment]
I tried the steps show here https://github.com/EmuELEC/EmuELEC/wiki/Bluetooth#notes--ps3-controllers

Emuelec-H3:~ # bluetootctl
-sh: bluetootctl: command not found
Emuelec-H3:~ # bluetoothctl
Agent registered
[bluetooth]# default-agent
Default agent request successful
[bluetooth]# power on
Changing power on succeeded
[bluetooth]# discoverable on
Changing discoverable on succeeded
[CHG] Controller 33:03:30:0A:55:AF Discoverable: yes
[CHG] Device 05:C3:97:85:63:25 Connected: yes
[Sony PLAYSTATION(R)3 Controller]# pairable on
Changing pairable on succeeded
[Sony PLAYSTATION(R)3 Controller]# scan on
Discovery started
[CHG] Device 0A:D6:89:8A:63:25 Connected: yes
[CHG] Device 05:C3:97:85:63:25 Connected: no

[CHG] Device 05:C3:97:85:63:25 Name: PLAYSTATION(R)3Conteroller-PANHAI
[CHG] Device 05:C3:97:85:63:25 Alias: PLAYSTATION(R)3Conteroller-PANHAI
[Sony PLAYSTATION(R)3 Controller]# trust 05:C3:97:85:63:25
Changing 05:C3:97:85:63:25 trust succeeded
[Sony PLAYSTATION(R)3 Controller]# connect 05:C3:97:85:63:25
Attempting to connect to 05:C3:97:85:63:25
[CHG] Controller 33:03:30:0A:55:AF Discoverable: no
[CHG] Device 05:C3:97:85:63:25 Connected: no
Failed to connect: org.bluez.Error.Failed
[CHG] Device 05:C3:97:85:63:25 Connected: yes
[PLAYSTATION(R)3Conteroller-PANHAI]#

the 05:C3:97:85:63:25 is the second controller.
and another thing the controller 1 that does pair , the lights stay blinking , the controller works but unstable sometimes drop connection then i click home it pairs again

**Comment by asakous** [comment]
I only have orapnge pi PC . since this board doesn't have BT . so I can't test the BT functionality.  try use Xbox360 wireless controller . it work out of box.

**Comment by asegura02** [comment]
i saw in batocera , they have  to set of drivers for sixad . one folder says official and other says shanwan , and in Retrorangepi they have also independent support for the official, gasia  and shanwan  , the problem with batocera is in my box it take too long to get the sd card to recognize to boot,  also memories over 32gb never boot , and with your emuelec -h3 boot fast it doesnt have the sd card size problem i have tested with 128gb. With one controller ps3 pairs but not fully because gets disconenncted very quick and , for some reason has this problem with the second one. here i uploaded the files i got from batocera maybe can give you a hint  https://www.mediafire.com/file/0yokdfxeyjoe1bp/sixad.zip/file

**Comment by asakous** [comment]
test new image . bluetooth problem should be fixed
