### ISSUE TITLE
Emuelec 4.2 pi pc no audio

### ISSUE THREAD

**Issue by caioeu19** [asakous/Neo-EmuELEC-H3#45]
i try in HDMI 1.0, 0.1,1.1,0.0 I've tried in all of these and none of the audio comes out

**Comment by asakous** [comment]
ES audio settings dosen't affect RA . you should bring up RA menu and change audio output setting. for example hw:0,0 or hw:0,1. or ssh into console and edit retroarch.conf.

**Comment by asakous** [comment]
#47
