### ISSUE TITLE
Copy Roms from USB

### ISSUE THREAD

**Issue by NewAgeRipper** [asakous/Neo-EmuELEC-H3#46]
I tried the copy roms from usb feature in the Original EmuElec and it worked fine. But in yours, it only seems to grab the first folder. In this case, atari2600. It doesn't get any of the other rom folders copied. I had my folder named "roms" and then inside each of the system folders. I also had the file created emuelec_copy_roms_from_here only in the roms folder. Not in any of the system folders. Any idea why it only transferred one folder and not any others? This is using an Allwinner H3 device.

**Comment by NewAgeRipper** [comment]
Als forgot to mention another issue or 2. I'm not getting any sound output. And the n64 cores need updating. Button functions work for a n64 game. But the toggle sticks and dpad do nothing. I would also suggest adding the n64 RICE core. And why doesn't remote ssh work for me either? I get Wi-Fi. I can scrape. But when I enter \\192.168.1.10, it says refused access.

**Comment by asakous** [comment]
for  sticks and dpad do nothing . try change retroarch controller setting to analog or digital.

**Comment by asakous** [comment]
> I tried the copy roms from usb feature in the Original EmuElec and it worked fine. But in yours, it only seems to grab the first folder. In this case, atari2600. It doesn't get any of the other rom folders copied. I had my folder named "roms" and then inside each of the system folders. I also had the file created emuelec_copy_roms_from_here only in the roms folder. Not in any of the system folders. Any idea why it only transferred one folder and not any others? This is using an Allwinner H3 device.

for no sound problem . just change retroarch audio out put setting . hw:0,0 or hw:0,1 . 
I am waiting EmuELEC to release a new version  so I can get update too.

**Comment by NewAgeRipper** [comment]
They did. It's v4.3.


-----Original Message-----

**Comment by NewAgeRipper** [comment]
> >
> for no sound problem . just change retroarch audio out put setting . hw:0,0 or hw:0,1 . 

That didn't help anything.

**Comment by asakous** [comment]
> > > 
> > 
> > 
> > for no sound problem . just change retroarch audio out put setting . hw:0,0 or hw:0,1 .
> 
> That didn't help anything.

there are only four options . hw:0,0 , hw:0,1 , hw:1,0 , hw:1,1 . one of them should work .
the steps are . change audio output , save config , restart game.

**Comment by asakous** [comment]
> They did. It's v4.3.
> […](#)
> -----Original Message----- From: Matthew Wang ***@***.***> To: asakous/Neo-EmuELEC-H3 ***@***.***> Cc: NewAgeRipper ***@***.***>; Author ***@***.***> Sent: Sat, Feb 5, 2022 4:01 am Subject: Re: [asakous/Neo-EmuELEC-H3] Copy Roms from USB (Issue #46) I tried the copy roms from usb feature in the Original EmuElec and it worked fine. But in yours, it only seems to grab the first folder. In this case, atari2600. It doesn't get any of the other rom folders copied. I had my folder named "roms" and then inside each of the system folders. I also had the file created emuelec_copy_roms_from_here only in the roms folder. Not in any of the system folders. Any idea why it only transferred one folder and not any others? This is using an Allwinner H3 device. for no sound problem . just change retroarch audio out put setting . hw:0,0 or hw:0,1 . I am waiting EmuELEC to release a new version so I can get update too.— Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

i mean 4.4

**Comment by NewAgeRipper** [comment]
Finally got sound. I had to change it to Sdl2 also. One other thing if you can tell me how to in detail.How can I add screenscraper.fr? You only have one scraper, and it doesn't have some of the game art for it's source.


-----Original Message-----

**Comment by asakous** [comment]
try new image.
