### ISSUE TITLE
All game systems slow now

### ISSUE THREAD

**Issue by NewAgeRipper** [asakous/Neo-EmuELEC-H3#47]
So once I got sound working on my 32gb crappy SD card, I decided to install this on a much better 64gb SD card. Every system I open. Atari2600, Mame, CPS, no matter they all run slow and sluggish. What did I do wrong? Are there settings I'm overlooking? But mostly each time I do a new flash, during initial setup for the first time, and on second boot or 3rd boot, I get a black bar with a lot of fast scrolling script errors. Is there a preferred software I should be using to flash the SD card with? I'm currently using Etcher.  

I think another problem could be, is that in the bios folder, there are no other machine folders. And the mame folder usually has a couple other machine core folders in it. At least EmuElec for Android boxes did. Batocera does. Your port doesn't. Am I supposed to add them?

**Edit:** OK so when I added all my bios files, something in there is affecting the performance of all the systems. When I don't add them, but only add what I need. then things seem to run fine. This did not happen with Batocera and it didn't happen with EmuElec for Android boxes. However, if we can smooth the next release out more. I'd prefer to use your port because it does boot every time. Batocera took 3 or 4 times in a row of hitting the power button to finally boot into it. But when it did load there were no issues.

Here's a tip also for H3 chips you might consider for listing for others who might have sound issues. Instead of changing 0,0 to something else for Retroarch, have them try Output/Audio/Device and scroll left or right and select hdmi:CARD=sndhdmi,DEV=0. That worked for me, and I didn't have to change anything else. But let visitors to your github know they will have to open Retroarch and go to Settings/User Interface/Show Advanced Settings. Because your build does not have that turned on by default. If I didn't know that when you told me to save config, like some total noob, then I would have to reply that I don't see "save config." You need to add more information in your release descriptions each time you release another build.

And every time I change a setting your current build freezes on me too. Almost every time.

**Comment by asakous** [comment]
if you don't mind , try 2.0 version . I think the SDL2 sound output is too much for H3 cpu. 
and I did not experienced any freezes while saving config. since I can't reproduce the problem . I think maybe just wait for next release and see the problem still exists or not.

**Comment by NewAgeRipper** [comment]
I fixed the sound issue by choosing another device method instead of 0,0 or 0,1 etc. It's just every time I saved a change in ES, ES would restart and then freeze or freeze after saving a setting in ES.


-----Original Message-----

**Comment by asakous** [comment]
try use new 4.5 image .

**Comment by asakous** [comment]
no response
