### ISSUE TITLE
All Winner H3 - Wifi Not Work

### ISSUE THREAD

**Issue by dieletro** [asakous/Neo-EmuELEC-H3#48]
**Describe the bug**
First of all, I want to congratulate you on the project!

The Wifi doesn't work on my TVBOX model, I did all the procedures to try to solve it, through retroARC, config file and manual introduction of the SSID and PASSWORD, but I was not successful.

I'm forwarding my screenshots so they can adjust to my chip model, if that's possible.

**Screenshots**

***SYSTEM***
![photo_2022-02-22_02-08-56](https://user-images.githubusercontent.com/11804577/155066907-f0ad3a69-ccfe-42d2-91f1-b00fc269c181.jpg)

***PROCESSOR***
![photo_2022-02-22_02-08-40](https://user-images.githubusercontent.com/11804577/155066905-6d6c3adf-6929-4dbd-a70c-79ea11e2945b.jpg)

![photo_2022-02-22_03-12-36](https://user-images.githubusercontent.com/11804577/155073446-b2131645-464e-4aa9-a855-6061afeef667.jpg)

**EmuELEC version:**
 - [Neo-EmuELEC-H3 V4.2](https://github.com/asakous/Neo-EmuELEC-H3/releases/tag/H3-v4.2)

**Comment by asakous** [comment]
what is your wifi chipset?

**Comment by asakous** [comment]
no response for long time.
