### ISSUE TITLE
4.2 for Orange Pi Plus 2E?

### ISSUE THREAD

**Issue by d-apps** [asakous/Neo-EmuELEC-H3#49]
Could you please build an image of emuELEC 4.2 for Orange Pi Plus 2E?
Thank you very much

**Comment by asakous** [comment]
I am merging EE 4.4 into this repo. please wait.

**Comment by d-apps** [comment]
Could you please check frontend music too? Plus 2e board have 2GB ram, It think it can handle background songs, actually I already tried other system like RetrOrangePi and frontend songs worked well but emulators are very outdated.

In Neo-EmuELEC 4.0 I have songs in roms/bgm folder, I get notifications like it is playing but there no sound.

Thank you very much.

**Comment by asakous** [comment]
I use analog outout as default development environment. maybe this cause problem.

**Comment by asakous** [comment]
4.5 released
