### ISSUE TITLE
Support for orange pi zero plus 2

### ISSUE THREAD

**Issue by lamerjack** [asakous/Neo-EmuELEC-H3#5]
I will try with orange pi one or orange pi pc plus that are very similar. (the first for memory the second for hardware addons)
Just i didn't understood how to use the bootloader.zip
for example if i want to do a orange pi plus i have to copy opipcplus.fex and rename to script.bin...
But i didn't understood what i have to do with boot.scr and uboot-sunxi-*
Than you very much, your distro is very impressive!!!!

**Comment by Broos-E** [comment]
i would also love to see support for the orangepi pc 2

**Comment by asakous** [comment]
sorry no H5 chipset support here. only H3.

**Comment by lamerjack** [comment]
orange pi zero plus 2 is also H3.
http://www.orangepi.org/OrangePiZeroPlus2/
smaller than orange pi one.
And with emmc wifi and bt.

**Comment by asakous** [comment]
I don't have any orange pi zero plus 2. even I make a image I still can't make sure it's a working image.

**Comment by lamerjack** [comment]
At the moment gift to you a OrangePIZeroPlus2 is little bit over my budget. But if you organize a donation link there will be my contribute and i'm sure that other people will donate!

**Comment by asakous** [comment]
I have a BPI-M2+ . the BPI company sent it to me long time ago.
I think . it's very similar to OrangePIZeroPlus2

from my test BPI-M2+ . 
1:wireless unstable
2:no bluetooth
3:sometimes I need to push reset bottom to boot system. 
4:occasionally crash.
others seems ok to me. 
if you don't mind. I build a image for  OrangePIZeroPlus2 next release.

**Comment by lamerjack** [comment]
I will test!
But consider about donations your work is really impressive!
