### ISSUE TITLE
Screen issue with HDMI-VGA adapter

### ISSUE THREAD

**Issue by Mister-SH** [asakous/Neo-EmuELEC-H3#50]
I have TV Box on Alwinner H3, Ram 512Mb (copy of Beelink X32, Sunvell R69). Connect to PC monitor via HDMI-VGA adapter. Emuelec 4.2 shows green screen
![25311637](https://user-images.githubusercontent.com/10107234/161377107-142d9a90-0787-4c61-bce3-b5364621d035.jpg)
![25311638](https://user-images.githubusercontent.com/10107234/161377108-46125705-71ac-464b-813b-e7649af15773.jpg)
**But (it's very important) Batocera, Lakka, Libreelec and other OS looks good via this adapter without changing any settings nor in monitor nor in OS**

**Comment by asakous** [comment]
I have no idea about this problem. since I use HDMI-VGA sometimes and It did not show such problem on my OPI PC. I leave this problem open.

**Comment by Mister-SH** [comment]
I find a reason. I add in script.bin
[hdmi_para]
**hdmi_cts_compatibility = 1**
And everything become good
