### ISSUE TITLE
Bluetooth connect with dongle

### ISSUE THREAD

**Issue by Mister-SH** [asakous/Neo-EmuELEC-H3#53]
Emuelec 4.5
TV-Box with Allwinner H3
Bluetooth dongle - Orico BTA-403. bluetooth 4.0
When I go to settings and try to connect Dualshock 4 nothing happens. Window (where pairing device write) in right up corner just blink.
Bluetooth dongle blink - there is a power on usb 2.0 port. So physically it works

**Comment by asakous** [comment]
The kernel that I use in this project is very old and may not work with new devices. (like Dualshock 4). 
I have no intention to fix any bluetooth controller problems. since H3 chip it''s old and not worth to fix it.
I am currently use xbox360 wireless controller, it works out of the box.

**Comment by Mister-SH** [comment]
In version 4.2 Emuelec try to connect with Dualshock or other bluetooth device and window appears but in version 4.5 window doesn't appear so Emuelec doesn't try to connect via bluetooth with any bluetooth device

**Comment by asakous** [comment]
since I working on another project. I am accidently find out what the problem are.  
It will be fixed next release.

**Comment by asakous** [comment]
@Mister-SH new image uploaded.

**Comment by Mister-SH** [comment]
I test new 4.5-1 and issue still exists. But...
I try to connect DS4 via BT from SSH and it connect. So, what we have
- from ES interface I can't connect DS4 via bluetooth - window just blink once
- I can connect DS4 by SSH commandline
When Emuelec loads in left top corner there is a log and there is an error **Can't run bluetooth agent** (something like this, don't remember exactly)

**Comment by asakous** [comment]
Yes . I think it's a Batocera Bluetooth agent problem. Since newer version of EmuELEC required  gobject-introspection package and I just couldn't get it compiled. So the best solution right now is put the Bluetooth connect commands into autostart.sh or custom_start.sh .  hopefully someone can fix this compile problem it in near future.

**Comment by shantigilbert** [comment]
> gobject-introspection package and I just couldn't get it compiled.

what was the error? I ran into a few issues with it as well

**Comment by asakous** [comment]
/home/matthew/Neo-EmuELEC-H3/build.EmuELEC-H3.arm-4.5/toolchain/lib/libgobject-2.0.a(gclosure.c.o): In function `value_to_ffi_type':
gclosure.c:(.text+0x213): undefined reference to `ffi_type_uint64'
gclosure.c:(.text+0x237): undefined reference to `ffi_type_sint64'
gclosure.c:(.text+0x257): undefined reference to `ffi_type_uint32'
gclosure.c:(.text+0x26f): undefined reference to `ffi_type_pointer'
gclosure.c:(.text+0x287): undefined reference to `ffi_type_sint32'
gclosure.c:(.text+0x29f): undefined reference to `ffi_type_double'
gclosure.c:(.text+0x2b7): undefined reference to `ffi_type_float'

upgrade gobject ? 

gobject-introspection also needs qemu . I guess this problem also exists.


another approach is to use Nuitka the Python Compiler . compile Batocera scripts into portable and executable scripts.

**Comment by shantigilbert** [comment]
Sorry I had a different issue, not sure how to fix that one, but it seems like its missing libfifi for whatever reason?

**Comment by asakous** [comment]
@shantigilbert  Now I got different error. It seems like pygobject problem. but I get it compiled. not sure why?

Traceback (most recent call last):
  File "/usr/bin/batocera/batocera-bluetooth-agent", line 14, in <module>
    from gi.repository import GLib
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3.7/site-packages/gi/__init__.py)

**Comment by asakous** [comment]
never mind . 
ln -sf _gi.cpython-37-x86_64-linux-gnu.so _gi.so seems fix the problem

**Comment by asakous** [comment]
seems work find now 

![image](https://user-images.githubusercontent.com/6611523/192710345-3b80acf0-0bd6-473e-b2f2-078833b246a7.png)

**Comment by shantigilbert** [comment]
Yeah that was the issue I was having, glad you figured it out.

**Comment by asakous** [comment]
no repsonse for long time . closed
