### ISSUE TITLE
Can nanopi m1 use this img？

### ISSUE THREAD

**Issue by Asterecho** [asakous/Neo-EmuELEC-H3#55]
Can nanopi m1 use this img？

Where Can i find the dtb file？

nanopi m1可以用这个镜像吗？我去哪里下载这个设备的dtb文件？

**Comment by asakous** [comment]
不知道。我沒這張版。您可試試直接用 opi pc 的 dtb 或projects/H3/sys_config 底下的 fex 轉 dtb 試試
