### ISSUE TITLE
H3 build vlc-3.0.16 fail aubot ld.gold: error: cannot find -lGL

### ISSUE THREAD

**Issue by txarmux** [asakous/Neo-EmuELEC-H3#56]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! EITHER USE THE FORUM (https://emuelec.org) OR USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!

EmuELEC$ git branch
* SDL_2.0.20
  dev

wtx@wtx:~/EmuELEC$ git log
commit c83f628215154d866ff87a4c3763e99c162d1063 (HEAD -> SDL_2.0.20, origin/SDL_2.0.20)
Author: shantigilbert <shantic@gmail.com>
Date:   Sun Mar 6 19:41:15 2022 -0600

    SDL2: Bump to 2.0.20

build :   PROJECT=Allwinner DEVICE=H3 UBOOT_SYSTEM=libretech-h3 ARCH=arm make image

err:
make[5]: Entering directory '/home/wtx/EmuELEC/build.EmuELEC-H3.arm-4/build/vlc-3.0.16/.armv7ve-libreelec-linux-gnueabihf/modules'
  CCLD     libhttps_plugin.la
  CCLD     libsimple_channel_mixer_plugin.la
  CCLD     libi420_nv12_plugin.la
  CCLD     libi420_10_p010_plugin.la
  CCLD     libmotion_plugin.la
  CCLD     libglspectrum_plugin.la
/home/wtx/EmuELEC/build.EmuELEC-H3.arm-4/toolchain/lib/gcc/armv7ve-libreelec-linux-gnueabihf/10.3.0/../../../../armv7ve-libreelec-linux-gnueabihf/bin/ld.gold: error: cannot find -lGL
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glEnable'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glEnable'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glDepthMask'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glMatrixMode'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glFrustum'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glMatrixMode'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glTranslatef'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glEnable'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glColorMaterial'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glEnable'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glLightfv'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glLightfv'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glShadeModel'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glBlendFunc'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glClear'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glPushMatrix'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glRotatef'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glPushMatrix'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glTranslatef'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glEnableClientState'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glEnableClientState'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glColor4f'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glVertexPointer'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glNormalPointer'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glDrawArrays'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glPopMatrix'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glTranslatef'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glPushMatrix'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glScalef'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glViewport'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glDisableClientState'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glDisableClientState'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glPopMatrix'
visualization/.libs/glspectrum.o:glspectrum.c:function Thread: error: undefined reference to 'glPopMatrix'
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:16010: libglspectrum_plugin.la] Error 1
make[5]: Leaving directory '/home/wtx/EmuELEC/build.EmuELEC-H3.arm-4/build/vlc-3.0.16/.armv7ve-libreelec-linux-gnueabihf/modules'
make[4]: *** [Makefile:28011: all-recursive] Error 1
make[4]: Leaving directory '/home/wtx/EmuELEC/build.EmuELEC-H3.arm-4/build/vlc-3.0.16/.armv7ve-libreelec-linux-gnueabihf/modules'
make[3]: *** [Makefile:12804: all] Error 2
make[3]: Leaving directory '/home/wtx/EmuELEC/build.EmuELEC-H3.arm-4/build/vlc-3.0.16/.armv7ve-libreelec-linux-gnueabihf/modules'
make[2]: *** [Makefile:1563: all-recursive] Error 1
make[2]: Leaving directory '/home/wtx/EmuELEC/build.EmuELEC-H3.arm-4/build/vlc-3.0.16/.armv7ve-libreelec-linux-gnueabihf'
make[1]: *** [Makefile:1450: all] Error 2
make[1]: Leaving directory '/home/wtx/EmuELEC/build.EmuELEC-H3.arm-4/build/vlc-3.0.16/.armv7ve-libreelec-linux-gnueabihf'
FAILURE: scripts/build vlc:target during make_target (default)
*********** FAILED COMMAND ***********
make ${PKG_MAKE_OPTS_TARGET}
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/install vlc:target has failed!

The following log for this failure is available:
  /home/wtx/EmuELEC/build.EmuELEC-H3.arm-4/.threads/logs/239.log

>>> vlc:target seq 239 >>>
[270/497] [FAIL] install vlc:target

The following log for this failure is available:
  /home/wtx/EmuELEC/build.EmuELEC-H3.arm-4/.threads/logs/239.log

Parallel build failure - see log for details. Time of failure: Sat Aug 12 05:35:54 UTC 2023
make: *** [Makefile:12: image] Error 1

sudo apt install gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev
sudo apt install libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev
sudo apt install libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev 
sudo apt installlibvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf xmlstarlet default-jre xsltproc
 is there any other tools I need to install ?
thanks!

**Comment by asakous** [comment]
try remove toolchain gl headers

**Comment by txarmux** [comment]
tks,it is pass
