### ISSUE TITLE
FATAL: kernel too old ERROR: can't resolve libraries to shared libraries: glib-2.0, gobject-2.0

### ISSUE THREAD

**Issue by txarmux** [asakous/Neo-EmuELEC-H3#58]
make[2]: Entering directory '/home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/.armv7ve-libreelec-linux-gnueabihf'
Making all in .
make[3]: Entering directory '/home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/.armv7ve-libreelec-linux-gnueabihf'
  CCLD     g-ir-generate
  CCLD     g-ir-inspect
  GEN      g-ir-scanner
  GEN      g-ir-annotation-tool
  GICOMP   /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/gir/DBus-1.0.gir
  GICOMP   /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/gir/fontconfig-2.0.gir
  GICOMP   /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/gir/freetype2-2.0.gir
  GICOMP   /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/gir/GL-1.0.gir
  GICOMP   /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/gir/libxml2-2.0.gir
  GICOMP   /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/gir/xft-2.0.gir
  GICOMP   /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/gir/xlib-2.0.gir
  GICOMP   /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/gir/xfixes-4.0.gir
  GICOMP   /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/gir/xrandr-1.3.gir
  GICOMP   /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/gir/win32-1.0.gir
  GICOMP   gir/cairo-1.0.gir
  GISCAN   GLib-2.0.gir
FATAL: kernel too old
ERROR: can't resolve libraries to shared libraries: glib-2.0, gobject-2.0
make[3]: *** [Makefile:3973: GLib-2.0.gir] Error 1
make[3]: Leaving directory '/home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/.armv7ve-libreelec-linux-gnueabihf'
make[2]: *** [Makefile:3088: all-recursive] Error 1
make[2]: Leaving directory '/home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/.armv7ve-libreelec-linux-gnueabihf'
make[1]: *** [Makefile:1637: all] Error 2
make[1]: Leaving directory '/home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/build/gobject-introspection-1.56.0/.armv7ve-libreelec-linux-gnueabihf'
FAILURE: scripts/build gobject-introspection:target during make_target (package.mk)
*********** FAILED COMMAND ***********
GI_CROSS_LAUNCHER="$TOOLCHAIN/bin/qemu-$TARGET_ARCH" GI_LDD=$TOOLCHAIN/bin/ldd-cross INTROSPECTION_SCANNER=$TOOLCHAIN/bin/g-ir-scanner-wrapper INTROSPECTION_COMPILER=$TOOLCHAIN/bin/g-ir-compiler-wrapper make
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/install gobject-introspection:target has failed!

The following log for this failure is available:
  /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/.threads/logs/288.log

>>> gobject-introspection:target seq 288 >>>
[288/497] [FAIL] install gobject-introspection:target

The following log for this failure is available:
  /home/wtx/disk/EmuELEC_4_5/build.EmuELEC-H3.arm-4/.threads/logs/288.log

Parallel build failure - see log for details. Time of failure: Wed Aug 23 05:55:25 UTC 2023
make: *** [Makefile:12: image] Error 1

EmuELEC_4_5$ PROJECT=Allwinner DEVICE=H3 UBOOT_SYSTEM=libretech-h3 ARCH=arm make image

when I build for H3, but gobject-introspection-1.56.0 is build fail。
FATAL: kernel too old？so I update the ubuntu from 18.04 to 20.04，but it is nothing help， so what should I do？

Linux version 4.15.0-213-generic (buildd@lcy02-amd64-079) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023

**Comment by asakous** [comment]
build command should be  PROJECT=H3 ARCH=arm DISTRO=EmuELEC UBOOT_SYSTEM=opipc make -j4 image . 
and there is no UBOOT_SYSTEM parameter libretech-h3

**Comment by asakous** [comment]
UBOOT_SYSTEM only accept below parameters
bpim2p
bx2
opi2
opilite
opione
opipc
opipcplus
opiplus
opiplus2e

**Comment by asakous** [comment]
my dev env is 18.04.1-Ubuntu x64  . use newer version of Ubuntu may cause problems.

**Comment by asakous** [comment]
no response . close.
