### ISSUE TITLE
Run Neo-Emuelec on banana pi m2 zero H3

### ISSUE THREAD

**Issue by Oberworld** [asakous/Neo-EmuELEC-H3#62]
It's possible to run Neo-Emuelec on a bpi-m2 zero H3 board?.
If so, what image should I use?.

Thanks in advance.

**Comment by asakous** [comment]
https://github.com/asakous/Neo-EmuELEC-H3/releases/tag/H3-v2.0 
download bpim2p image . maybe works. not sure.

**Comment by asakous** [comment]
no response
