### ISSUE TITLE
Where are the retroarch cores stored?

### ISSUE THREAD

**Issue by juliotec** [asakous/Neo-EmuELEC-H3#63]
Hi, I created the sdcard and my system boot ok, but I have been searchng the retroarch cores, where are they stored, I searched in EMUELEC partition, Storage partition and eeroms partition, where are they?

**Comment by asakous** [comment]
emuelec uses Squashfs . all system files are in SYSTEM image.

**Comment by asakous** [comment]
no response . closed.
