### ISSUE TITLE
FAILURE: scripts/install rclone has failed!

### ISSUE THREAD

**Issue by 986046679** [asakous/Neo-EmuELEC-H3#64]
Hello Author, when I was compiling your project, I encountered an installation error. How should I handle it?
![a5becb37df51bfd96614f0df9eac48d](https://github.com/user-attachments/assets/891517f4-dbe4-42cd-9be5-e2203a43b82f)
When I replaced the version in the go.mod file with the latest version, the following error message appeared again.
![image](https://github.com/user-attachments/assets/d36b87c9-bdee-49dd-adc6-bd0e814d83e8)

**Comment by asakous** [comment]
os / gcc version ？

**Comment by asakous** [comment]
use ubuntu 20.04. Don't use other distro. it may cause compile problems.

**Comment by 986046679** [comment]
> use ubuntu 20.04. Don't use other distro. it may cause compile problems.

Hello, Matthew Wang. I have successfully resolved the error in the project and compiled it. However, I have a request. I have a box with an H313 chip and no one has adapted this chip model on the internet. So now I'm trying to adapt Emuelec on H313. But since I'm not familiar with the code structure of Emuelec, could I ask for your help to adapt H313? Currently, I have successfully run the Tina system on the H313 device, but I'm still confused about the next series of adaptations. I wonder if you could offer me some assistance.

**Comment by asakous** [comment]
as far as know . there is no working linux with mali gpu driver for H313.  just use pegasus frontend with retroarch android version instead . 
You might want to try MESA. gpu driver  If so .  You will faceing performance issues.

**Comment by 986046679** [comment]
> as far as know . there is no working linux with mali gpu driver for H313. just use pegasus frontend with retroarch android version instead . You might want to try MESA. gpu driver If so . You will faceing performance issues.

Tina is a system derived from the Linux kernel developed by Allwinner. Shouldn't it be similar to Linux? And as far as I know, H3 seems to be the Linux version of Tina. You should be using the Emuelec adapted for H3's Tina, right?

**Comment by 986046679** [comment]
And as far as I know, the GPU integrated in the H313 chip is Mali-G31 MP2. Does this mean it has a Mali GPU driver? As long as it exists, I can obtain it. But the problem is that I'm still confused about how to port it to Emuelec. Since you have ported H3 before, I think you are an expert in this field. So I'm asking if you could offer me some help to smoothly run Emuelec on H313.

**Comment by asakous** [comment]
basically you need to find a linux distribution with working mali GPU driver . just like car (H313 chip) without gas (GPU driver) you still can't drive the car. 
Since mali GPU driver is ARM property , usually not include in linux distribution . If you can find one then porting became feasible.

**Comment by 986046679** [comment]
I have obtained the mali gpu driver with 32bit 64bit armh, and confirmed that it can run on tina system developed by ALLwinner with linux kernel, so can we add a wechat so that you can guide me better

**Comment by 986046679** [comment]
![d9caa19446cc29f04def8da58da62ee](https://github.com/user-attachments/assets/588f7f2d-43d0-46db-b0e8-5cea29bdec76)
This is my wechat QR code, looking forward to your reply

**Comment by asakous** [comment]
You have to run glmark to ensure driver is work probably .  wechat  ==> No .

**Comment by 986046679** [comment]
I will try, and I'm sorry for the inconvenience caused by adding wechat, because I just want to facilitate our better communication, because github may not be able to contact you in time

**Comment by 986046679** [comment]
> You have to run glmark to ensure driver is work probably . wechat ==> No .
I am sorry that I am relatively new to tina system, so I am confused about how to use tina and whether glmark verification driver works probably . Could you please give me some help to complete the verification of this step

**Comment by asakous** [comment]
https://www.youtube.com/watch?v=TMj9qu5oFHM
the fps should better then video clip

**Comment by 986046679** [comment]
I am very sorry that I am still confused about tina. As for what you said, I tried to find the glmark2_arm project and tried to cross-compile it to use it on tina. Unfortunately, the necessary libraries were missing in tina's compilation chain, so the project could not be successfully compiled. Therefore, I would like to ask how you successfully ran glmark in tina when adapting H3 at that time. Can I learn from your way to run it

**Comment by 986046679** [comment]
你好，我刚了解到，H313上好像也可以跑ubuntu，如果可以跑ubuntu，是否可以替换掉Tina去编译emuelec的启动boot等

**Comment by asakous** [comment]
You need to make sure the linux distribution is working on your H313 tvbox/board . for example . NAND / Network / Wifi.
in the Linux desktop environment  run glmark2 .  the FPS should >=70 . If so , then you can go to next step poting kernel/uboot/dtb .... to EmuELEC

**Comment by 986046679** [comment]
You mean that I, for example, need to make sure that ubuntu can run on H313 boards and run glmark2 FPS>=70, so it makes sense to port, if it is less than 70, there is no sense to port again, right

**Comment by asakous** [comment]
Yes

**Comment by 986046679** [comment]
你好，我想问一下能跳过这个glmark这一步吗，因为据我所知我现在在板上跑的这个ubuntu是跑过ppspp以及其他模拟器的，这是不是就意味着他的性能是可以顶的住的，如果能跳过glmark这一步的话，那我下一步的具体步骤需要怎么做

**Comment by 986046679** [comment]
并且通过询问，曾经也跑过retroarch

**Comment by 986046679** [comment]
Can I add your contact information? If wechat is not convenient, it can also be something else. I mainly want to be able to contact you in time. Besides, I think you have transplanted Allwinner and with your help, I can quickly implement emuelec on H313. If necessary, I can also pay some remuneration as the cost of study.

**Comment by 986046679** [comment]
#Is that okay？

**Comment by asakous** [comment]
contact  asakous@yahoo.com.tw
