### ISSUE TITLE
Save new configuration Core on Retroarch

### ISSUE THREAD

**Issue by batistars3** [asakous/Neo-EmuELEC-H3#8]
Hello, I'm having trouble saving new configurations for each core, there is no option in retroarch. How to enable? I've seen several videos, but don't have the option. And great work you are doing for H3, especially for Orange Pi PC.

**Comment by asakous** [comment]
settings > User Interface, enable Advanced Settings.
or when you playing games -> pause game -> bring up Retroarch menu ->scroll down , there is a option that you can save .
